[plugin]
repository = "https://github.com/sharkycorps/Artisan.git"
commit = "552a3f4413b6a63c804ce2da74d113f0d1a644aa"
owners = [ "Taurenkey (Puni.sh)", "sharkycorps" ]
project_path = "Artisan"
changelog = ''''''