[plugin]
repository = "https://github.com/sharkycorps/Artisan.git"
commit = "acdd535828918e10029b0fdf143c799f8e7e2e51"
owners = [ "Taurenkey (Puni.sh)", "sharkycorps" ]
project_path = "Artisan"
changelog = ''''''