[plugin]
repository = "https://github.com/sharkycorps/Artisan.git"
commit = "0a0976995595246ba3203467edc18f8404676092"
owners = [ "Taurenkey (Puni.sh)", "sharkycorps" ]
project_path = "Artisan"
changelog = ''''''