[plugin]
repository = "https://github.com/sharkycorps/BDTHPlugin.git"
commit = "520a4f710846259216f8292d38d311eb2df1ce6f"
owners = [ "LeonBlade", "sharkycorps" ]
project_path = "BDTHPlugin"
changelog = ''''''