[plugin]
repository = "https://github.com/sharkycorps/TextAdvance.git"
commit = "8973e4c06488ad2cdd993139616a54df345f6de9"
owners = [ "NightmareXIV", "sharkycorps" ]
project_path = "TextAdvance"
changelog = ''''''