[plugin]
repository = "https://github.com/HirotaZX/InventoryTools.git"
commit = "cbbb743a261d6309450bf764327b4a86ee4d0fe4"
owners = [ "Critical_Impact" ]
project_path = "InventoryTools"
version = "1.7.0.2"
changelog = ''''''