[plugin]
repository = "https://github.com/HirotaZX/InventoryTools.git"
commit = "2aead968ab198369f32dbcf776824420fce66f50"
owners = [ "Critical_Impact" ]
project_path = "InventoryTools"
version = "1.7.0.2"
changelog = ''''''