[plugin]
repository = "https://github.com/HirotaZX/InventoryTools.git"
commit = "4cb9ad371a56ad959c79f7f4b7f124663c4013bc"
owners = [ "Critical_Impact" ]
project_path = "InventoryTools"
version = "1.7.0.2"
changelog = ''''''