[plugin]
repository = "https://github.com/sharkycorps/InventoryTools.git"
commit = "aa8cdc1382ce2b6beb5d5aa9ee9a19454c5f4f83"
owners = [ "Critical_Impact", "sharkycorps" ]
project_path = "InventoryTools"
version = "1.7.0.20"
changelog = ''''''