[plugin]
repository = "https://github.com/sharkycorps/InventoryTools.git"
commit = "fb71bce6dbe3d586f8e7230d9605570c10042e9c"
owners = [ "Critical_Impact" ]
project_path = "InventoryTools"
version = "1.7.0.2"
changelog = ''''''