[plugin]
repository = "https://github.com/sharkycorps/AntiAfkKick.git"
commit = "6b5b842d2269019921d5a189b692aa99507cf6a3"
owners = [ "NightmareXIV", "sharkycorps" ]
project_path = "AntiAfkKick-Dalamud"
changelog = ''''''